version: '2'

services:

  joe.example.com:
    container_name: joe.example.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=JoeMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    depends_on:
      - kafka.joe.example.com
    volumes:
      - ../crypto/ordererOrganizations/example.com/orderers/joe.example.com/msp:/var/hyperledger/orderer/msp
      - ../crypto/ordererOrganizations/example.com/orderers/joe.example.com/tls/:/var/hyperledger/orderer/tls
      - ../config/genesis.block:/var/hyperledger/orderer/genesis.block

  p0.clark.example.com:
    container_name: p0.clark.example.com
    extends:
      file: peer.yaml
      service: peer
    environment:
      - CORE_PEER_ADDRESS=p0.clark.example.com:7051
      - CORE_PEER_LOCALMSPID=ClarkMSP
      - CORE_PEER_ID=Clark
    depends_on:
      - joe.example.com
    volumes:
      - ../crypto/peerOrganizations/clark.example.com/peers/p0.clark.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto/peerOrganizations/clark.example.com/peers/p0.clark.example.com/tls:/etc/hyperledger/fabric/tls

  p0.amelia.example.com:
    container_name: p0.amelia.example.com
    extends:
      file: peer.yaml
      service: peer
    environment:
      - CORE_PEER_ADDRESS=p0.amelia.example.com:7051
      - CORE_PEER_LOCALMSPID=AmeliaMSP
      - CORE_PEER_ID=Amelia
    depends_on:
      - joe.example.com
    volumes:
      - ../crypto/peerOrganizations/amelia.example.com/peers/p0.amelia.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto/peerOrganizations/amelia.example.com/peers/p0.amelia.example.com/tls:/etc/hyperledger/fabric/tls

  admin.clark.example.com:
    container_name: admin.clark.example.com
    extends:
      file: admin.yaml
      service: admin
    environment:
      - CORE_PEER_ADDRESS=p0.clark.example.com:7051
      - CORE_PEER_LOCALMSPID=ClarkMSP
    depends_on:
      - joe.example.com
      - p0.clark.example.com
    volumes:
      - ../crypto/peerOrganizations/clark.example.com/users/Admin@clark.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto/peerOrganizations/clark.example.com/users/Admin@clark.example.com/tls:/etc/hyperledger/fabric/tls
      - ../crypto/ordererOrganizations/example.com/orderers/joe.example.com/msp/tlscacerts/tlsca.example.com-cert.pem:/etc/hyperledger/fabric/joe.example.com-tls-ca.pem
  
  admin.amelia.example.com:
    container_name: admin.amelia.example.com
    extends:
      file: admin.yaml
      service: admin
    environment:
      - CORE_PEER_ADDRESS=p0.amelia.example.com:7051
      - CORE_PEER_LOCALMSPID=AmeliaMSP
    depends_on:
      - joe.example.com
      - p0.amelia.example.com
    volumes:
      - ../crypto/peerOrganizations/amelia.example.com/users/Admin@amelia.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto/peerOrganizations/amelia.example.com/users/Admin@amelia.example.com/tls:/etc/hyperledger/fabric/tls
      - ../crypto/ordererOrganizations/example.com/orderers/joe.example.com/msp/tlscacerts/tlsca.example.com-cert.pem:/etc/hyperledger/fabric/joe.example.com-tls-ca.pem
  
  zookeeper.joe.example.com:
    container_name: zookeeper.joe.example.com
    image: hyperledger/fabric-zookeeper:latest
    restart: always

  kafka.joe.example.com:
    container_name: kafka.joe.example.com
    image: hyperledger/fabric-kafka:latest
    restart: always
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper.joe.example.com:2181
      - KAFKA_MESSAGE_MAX_BYTES=52428800 # 50 MiB should be enough
      - KAFKA_REPLICA_FETCH_MAX_BYTES=52428800
      - KAFKA_LISTENERS=EXTERNAL://0.0.0.0:9092,REPLICATION://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL://kafka.joe.example.com:9092,REPLICATION://kafka.joe.example.com:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,REPLICATION:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=REPLICATION
    depends_on:
      - zookeeper.joe.example.com