Profiles:
    SystemGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *Joe
        Consortiums:
            MyConsortium:
                Organizations:
                    - *Clark
                    - *Amelia
    ClarksChannel:
        Consortium: MyConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Clark

Organizations:
    - &Joe
        Name: Joe
        ID: JoeMSP
        MSPDir: ../crypto/ordererOrganizations/example.com/msp
    - &Clark
        Name: Clark
        ID: ClarkMSP
        MSPDir: ../crypto/peerOrganizations/clark.example.com/msp
        AnchorPeers:
            - Host: p0.clark.example.com
              Port: 7051
    - &Amelia
        Name: Amelia
        ID: AmeliaMSP
        MSPDir: ../crypto/peerOrganizations/amelia.example.com/msp
        AnchorPeers:
            - Host: p0.amelia.example.com
              Port: 7051

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - joe.example.com:7050
    BatchTimeout: 1s
    BatchSize:
        MaxMessageCount: 100
        AbsoluteMaxBytes: 10 MB
        PreferredMaxBytes: 512 KB
    Organizations:

Application: &ApplicationDefaults
    Organizations:
